name: Generate Sitemap

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Щоденне оновлення о 00:00 UTC

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url: "https://switchplayer.xyz"

      - name: Commit and push sitemap
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Auto-generate sitemap" || echo "No changes to commit"
          git push
        env:
          git push "https://x-access-token:${{ secrets.PAT }}@github.com/latsuha/SwitchPlayer.git" HEAD:main



